### ISSUE TITLE
破折號位置錯誤

### ISSUE THREAD

**Issue by cathree3** [ButTaiwan/genyo-font#1]
![2017-08-19 10 37 04](https://user-images.githubusercontent.com/13507992/29487622-0424ada0-852f-11e7-9230-c7c10ed6fd6c.png)

豎排時破折號位置錯誤、軟件是 Adobe 的 Ai、左側爲「思源宋體」對比。
無標點擠壓等設定、Kerning 選擇默認。

**Comment by ButTaiwan** [comment]
感謝回報問題。
此問題確認原因在.otf轉換成.ttf時，FontForge計算vmtx的錯誤。

由於這部分有點複雜，可能需要一段時間研究怎麼排除問題。

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/29489192-b9568914-854d-11e7-8f26-c7dbb1bb12c5.png)

找到解法解決了。
同時也修改了省略號問題（讓Illustrator不會一直選到歐文置底版本），另外同時拿掉漢字「一」直排時的壓縮。

預計下一版本時一起更新（請稍待數天～數週）。

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/29576859-fd7847b8-879b-11e7-81c5-3dc6edef4c58.png)
