### ISSUE TITLE
關於間隔號「·」(U+00B7)

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#14]
源樣明體系列的間隔號「·」(U+00B7)可否改成全形的間隔號呢？這符號在繁體中文上比較常用全形的。

**Comment by KrasnayaPloshchad** [comment]
不知道您用「‧」(U+2027)以後效果如何，如果可以，就用這個替代吧。

**Comment by KrasnayaPloshchad** [comment]
我發現思源宋體的間隔號(U+00B7)都是半形的，所以建議改用連字點(U+2027)。
