### ISSUE TITLE
源樣明體和思源宋體在 LibreOffice 當中的兩個不一樣的表現

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ButTaiwan/genyo-font#15]
1. 行距不一致
在沒有任何改動的情況下源樣明體的行距明顯偏窄
![圖一](https://i.imgur.com/kgK77Tu.png)
2. 粗體顯示異常
點選工具列上面的加粗按鈕以後，源樣明體只能被暴力加粗，而思源宋體能調用粗體版本
![圖二](https://i.imgur.com/WeCwTGz.png)

**Comment by ButTaiwan** [comment]
源樣系列行距改窄是故意的 (feature)。
因為思源系列預設行高，在Word預設12pt的行高下就會佔兩行，造成一般使用上的不便。
故本系列刻意調整過行高，這有寫在說明文件裡。

![image](https://user-images.githubusercontent.com/5418570/47191022-5b3b9300-d377-11e8-9c38-7dbbf0527c64.png)

**Comment by KrasnayaPloshchad** [comment]
> 源樣系列行距改窄是故意的 (feature)。

原來是這樣啊，我明白了。

> 粗體的問題另外測試。

那就看用戶需求了。不過我在 [Wikipedia](https://en.wikipedia.org/wiki/Source_Han_Serif) 上查了，思源宋體就是用了 font link，難怪 LibreOffice 怎麽可以調用粗體。
![screenshot_2018-10-19 source han serif - wikipedia](https://user-images.githubusercontent.com/10364351/47225462-aa9cb600-d3ad-11e8-87a9-25ebbe5082fd.png)
