### ISSUE TITLE
源X明朝 JP 缺「砸」字

### ISSUE THREAD

**Issue by lapomme** [ButTaiwan/genyo-font#17]

**Comment by ButTaiwan** [comment]
已發現此問題。
本以為JP版本部分有收Big5所有字，但似乎還是只有日文漢字。（因為一些Bug...）

此問題有點複雜。
因為JP版本就算收了日文沒有的漢字，那又該採用TW字型還是KR字形呢？
我要花時間整理一下 policy。
由於影響很大，應該會是下一個大改版時才處理。

**Comment by ButTaiwan** [comment]
V1.500 起 TW 與 JP 合併為一個 ttc 檔案釋出，不再分成兩個字型檔。
故已經沒有收錄字數不同的問題。
