### ISSUE TITLE
關於Word中，破折號「─」(U+2500)直書的方向問題

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#19]
如下圖所示，在Word中以源樣系列TW版編排文件時，發現大多數的符號（刪節號、波浪號）皆能正確轉為直式，但兩個「─」(U+2500)破折號卻未能轉成直式；但將字型換成源樣系列JP版後，破折號就能轉成直式了。請問這是刻意這樣設定的嗎？
![01](https://user-images.githubusercontent.com/42777336/49325869-7b6c8d80-f584-11e8-8201-644c04b5ea3d.jpg)

**Comment by ButTaiwan** [comment]
我重現不了耶？

![image](https://user-images.githubusercontent.com/5418570/49326236-26337a80-f58a-11e8-97ef-e4a8fd720234.png)

**Comment by ButTaiwan** [comment]
其實源樣系列，打兩個全形減號－也會被接成破折號 :P

**Comment by chlbc** [comment]
不過不知為何，我這裡不但除了破折號之外，連全形減號、HYPHEN(‐)、EN DASH(–)，甚至是EM DASH(—)都沒辦法順利翻轉。我是用Word2010，是版本問題、還是設定問題嗎

**Comment by chlbc** [comment]
回報：換了Word2016來開就能正常轉成直式的了，因此應該是Word2010的問題

**Comment by ButTaiwan** [comment]
Ver 1.500 起，破折號定義為兩個 U+2014 或兩個 U+2015。
即 —— 或 ――。

舊版的兩個全形減號－－不再支援。
另外，U+2500 ── 是表格符號，也不適合做為破折號，不支援。
