### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by EpsilonCHC** [ButTaiwan/genyo-font#2]
建議可以做一個新的類型的明體，有種強迫症叫，想把諺文改成老明體（類似朝鮮的光明體，韓國已廢），日文假名也改成明體筆意（非楷體筆意）.
U can create a new type of Mingti, there is a kind of obsession taken by the persons who want to change new Korean Mingti into old Korean Mingti, just like Kwangmingti in N. Korean which was repealed in S. Korean, and the kana in Japanese into Minti instead of quasi-Kaiti.

**Comment by ButTaiwan** [comment]
這不是本計畫的範疇啊。
本計畫是「從思源宋體各語言版本挑選適合字符」出來組成傳統印刷體風格字型。
（再以程式自動處理，作出源流、源雲等加工造型）
並不自行製作任何新字符。
