### ISSUE TITLE
可以給「源系列」增加JP版标点的TW版字形版本吗？

### ISSUE THREAD

**Issue by cathree3** [ButTaiwan/genyo-font#20]
方便緊排，也符合中馬星等其他地區繁體字使用者習慣。

**Comment by ButTaiwan** [comment]
目前發表之字型檔容量已經過多，只為了標點多一倍容量，我自己是意願比較低啦。
有興趣做的人可以自己fork！

**Comment by KrasnayaPloshchad** [comment]
Unicode 12.0 引入了運用 VS 字元切換標點字形的方法，并且思源黑體 2.000 已經實作，建議嘗試。
https://www.unicode.org/versions/Unicode12.0.0/

**Comment by KrasnayaPloshchad** [comment]
Unicode 官方發佈了一個 Standardized Variants 資料，值得參考，其中 East Asian punctuation positional variants 這一節規定了如何運用 VS 字元實作標點的變體。
https://www.unicode.org/Public/UNIDATA/StandardizedVariants.txt
現時思源黑體 2.000 已有實作。

**Comment by ButTaiwan** [comment]
就像去調整標點寬度、字高等動作，這專案初衷是想要把用 Adobe 專業軟體才能順利操作的思源系列，改造成一般 Office 軟體就能容易使用的字型。
加上太多 OpenType features 或 IVS / VS，又讓這字型變得很複雜，感覺就有遠離初衷了...
