### ISSUE TITLE
请问一下会做CN版的源樣黑體和源樣明體吗？

### ISSUE THREAD

**Issue by Seekladoom** [ButTaiwan/genyo-font#22]
想问一下大大之后会不会做CN版的源樣黑體和源樣明體的TTF转换并修正竖排字号，高基线以及部分西文和标点符号的问题？CN版的修改可以参考一下方正字库的方正雅宋系列和方正兰亭黑系列的标点符号做修改。如果没空的话，可以问一下是用什么软件进行这些处理的？

如有冒犯还请多多包涵。

**Comment by ButTaiwan** [comment]
不會。

大部分的處理是自己寫程式的。
過程用到的工具包括 AFDKO、ttx、otfcc、imagick、potrace 。
