### ISSUE TITLE
“又”字無提筆

### ISSUE THREAD

**Issue by NSKernel** [ButTaiwan/genyo-font#23]
雖然在您給出的README中的更新紀錄中提及了對“又”字添加了提筆，但是無論更新紀錄的截圖還是實際的TTF文件中均無。
<img width="620" alt="スクリーンショット 2019-09-03 14 42 17" src="https://user-images.githubusercontent.com/30398939/64149879-b5dbc180-ce59-11e9-993d-3922557b4cd8.png">
左爲當前版本的“又”字，右爲有提筆的樣式。
據康熙字典而言“又”字當有提筆
<img width="133" alt="スクリーンショット 2019-09-03 14 44 34" src="https://user-images.githubusercontent.com/30398939/64149899-bc6a3900-ce59-11e9-8fb4-2d506579ecad.png">
此問題亦見於源流明朝。不知是bug還是有意而爲之？^w^

**Comment by Seekladoom** [comment]
老哥你回错人了，你应该找ButTaiwan而不是我。。。_(:з」∠)_




------------------ 原始邮件 ------------------
发件人: "NSKernel"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 下午2:49
收件人: "ButTaiwan/genyo-font"<genyo-font@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ButTaiwan/genyo-font] “又”字無提筆 (#23)




雖然在您給出的README中的更新紀錄中提及了對“又”字添加了提筆，但是無論更新紀錄的截圖還是實際的TTF文件中均無。
 
 左爲當前版本的“又”字，右爲有提筆的樣式。
 據康熙字典而言“又”字當有提筆
 
 此問題亦見於源流明朝。不知是bug還是有意而爲之？^w^

**Comment by NSKernel** [comment]
呃我是新开了个issue呀，看您收到了这个提示的话是不是因为subscribe了所有的issue？

**Comment by ButTaiwan** [comment]
這個字應該是思源本身就沒有收有提筆的版本，沒得選。（叉字有，又字卻沒有。）
