### ISSUE TITLE
豎排「〱、〲」（くの字点）字位問題

### ISSUE THREAD

**Issue by edward-martyr** [ButTaiwan/genyo-font#24]
豎排時「〱、〲」兩個日文記號以及「〳〵、〴〵」兩對ligature字位明顯向上偏移了，請修復。

**Comment by ButTaiwan** [comment]
Ver 1.500 test OK in Microsoft Word.
![image](https://user-images.githubusercontent.com/5418570/79039050-1792b400-7c11-11ea-8f31-891a05c98d4c.png)
