### ISSUE TITLE
建議更換「鶿」的字形對應

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#25]
如題，源樣系列的「鶿」字目前是採用思源KR的字符；但思源JP的「鶿」字與康熙字典中的舊字形較為相近，因此建議將源樣系列的「鶿」字更換為思源JP的字符。
![鶿](https://user-images.githubusercontent.com/42777336/72809507-b654e780-3c96-11ea-98be-5a36919843dc.jpg)

**Comment by ButTaiwan** [comment]
fixed in Ver 1.500
![image](https://user-images.githubusercontent.com/5418570/79039040-efa35080-7c10-11ea-87ad-05a5781ec4f1.png)
