### ISSUE TITLE
仮名、かぎ括弧は等幅がデフォルトの方が使いやすいです

### ISSUE THREAD

**Issue by yama-ver2** [ButTaiwan/genyo-font#26]
ご要望失礼いたします。
現状、ほとんどのフォントは等幅の仮名・かぎ括弧がデフォルトだと思いますし、個人的には本文・長文でのプロポーショナル仮名は読みづらいです。

デザイン用途ではOpenTypeフィーチャータグを使えるプログラム（Illustratorなど）を使うことが多いと思われますので、等幅がデフォルトでも困ることは少ないのではないでしょうか。

**Comment by ButTaiwan** [comment]
どのプログラムでのご利用ですか？

動画字幕ソフトやPowerPointなどのスライドなど、OpenTypeタグが使えないが文字をできるだけ詰めたい使用例も多かったです。特に源流・源雲・源石・源泉シリーズの仮名は小さくしたため、スライドなどでの利用ではアキが大きい悩みもありました。
以上の理由を踏まえて実験的にプロポーションにしてみました。

その代わり全角のほうをfwid, salt, ss01フィーチャーに入れましたので、全角が望ましい本文組みの場合、たとえばWordなら「フォント＞詳細設定＞スタイルセット＞1」に設定したら全角仮名と全角括弧が出ます。

![image](https://user-images.githubusercontent.com/5418570/82745839-52b10700-9dbb-11ea-921e-9040c80f2d44.png)

**Comment by yama-ver2** [comment]
源流明朝などは伝統的なデザインなのでワープロソフトで本文書体に愛用していますが、デフォルトがプロポーショナルだと等幅に変更するのに一手間かかりますので、できればすぐに等幅を選べた方がありがたいです。

OpenTypeタグが使えない環境ですとゲームのテキスト表示やテキストエディターなどでも利用していますが、これらも等幅で使いたいです。
（最近のコンシューマーゲームでもテキスト表示は等幅の方が多いです。プロポーショナルで使用しているものもないことはないですが、ウェイトがかなり大きいか、ふところが広い書体が多く選ばれているようです。）

ファイルサイズが増える問題はあると思いますが、従来のTrueTypeフォントのように等幅フォントとPフォントがファミリーで分かれていれば最も使い勝手は良いように思います。

**Comment by ButTaiwan** [comment]
そうですね。確かに等幅とプロポーション両方もあれば一番良いですね。

実は v1.500 から .ttc にしましたので、両方作っても最終のフォントサイズはほぼ変わりません（グリフデータが同じなので合併はできます。違うのはcmapとnameテーブルだけ）。
（ただインストールされるフォントはTW・JPそれぞれの等幅・Pの4つになります。システムフォントリストに表示されるフォント数は一気に増えます。）

ただ実際の作業中に一旦4つのフォントファイルにしてからまた .ttc に合併すること必要があります。現在のプロセスは、まずOTFの状態ですべての処理を行い、リリースする直前にTTF化にしていますので、等幅verも同じプロセスで作りますと相当な処理時間がかかります（TTF化の計算が遅いので）。
新たにTTF化した状態でcmapとnameテーブルの入れ替えのプロセスを作り直す必要があります。

宿題とさせていただきます。

**Comment by yama-ver2** [comment]
ご検討いただければ幸いです。
等幅がメインの用途ではv1.300を引き続き利用させていただこうと思います。

**Comment by ButTaiwan** [comment]
V2.000 がリリースされました。
等幅（無印）とプロポーション（P印）の２フォントに分けました。
