### ISSUE TITLE
台語羅馬字少了大寫的鼻音符號

### ISSUE THREAD

**Issue by cathree3** [ButTaiwan/genyo-font#28]
ᶰ ᴺ

**Comment by ButTaiwan** [comment]
未來版本大概會處理。
目前請盡量用台羅的NN。

**Comment by KrasnayaPloshchad** [comment]
Adobe 自己也沒有加這兩字，所以我給他們發了個 issue
https://github.com/adobe-fonts/source-serif-pro/issues/82

**Comment by ButTaiwan** [comment]
V2.000 已加上 ᴺ。
