### ISSUE TITLE
OTF Version?

### ISSUE THREAD

**Issue by ayaka14732** [ButTaiwan/genyo-font#29]
Currently, only TTF version is available. However, considering that Source Han Serif itself is OTF, there can be an OTF version alongside the TTF version as well.

**Comment by ButTaiwan** [comment]
I didn't release OTF files In order to avoid confusing with choosing font file type.
What kind of situation that you need the OTF ones?

故意不公開OTF是為了減少版本的混亂（還有name table衝突等問題）。
實際上OTF跟TTF的差異只在render engine、hinting方式上，對OpenType支援是相同的。有什麼非需要OTF不可的情境嗎？

**Comment by ayaka14732** [comment]
是因為我感覺與思源宋體相比，源樣明體的顯示效果有時會不清晰，有人告訴我這是 hinting 的方式不同導致的。

**Comment by ButTaiwan** [comment]
沒有錯。
但是除了源樣以外，源流、源雲、源石、源泉動了外框的關係，hiniting資料全部丟失了。
就算是OTF，也是毫無hinting資訊的狀態。

**Comment by ayaka14732** [comment]
感謝解答！還是希望可以釋出 OTF 版本，即使作為另一專案亦可。

**Comment by Marcus98T** [comment]
另一個理由是為了forks，如果某個人想要自己改變這個字體系列，現在的情況還是不可能的，因為在使用自動化工具時，[TTF版本的Bézier curves使得不可能做的](https://github.com/welai/glow-sans/issues/8#issuecomment-631205665)。如果有OTF版的話，那麼forks也可以使用這個字體系列作為基礎，Shippori Antique/Mincho 也是這樣嘛。

**Comment by ButTaiwan** [comment]
> 另一個理由是為了forks，如果某個人想要自己改變這個字體系列，現在的情況還是不可能的，因為在使用自動化工具時，[TTF版本的Bézier curves使得不可能做的](https://github.com/welai/glow-sans/issues/8#issuecomment-631205665)。如果有OTF版的話，那麼forks也可以使用這個字體系列作為基礎，Shippori Antique/Mincho 也是這樣嘛。

那單純只是 Glow Sans 寫的工具如此，並不是 TTF 無法編輯。

**Comment by ayaka14732** [comment]
@Marcus98T Not related to the current project, but I am now using [redchenjs/source-han-serif-classic](https://github.com/redchenjs/source-han-serif-classic). You can check if this meet your needs.

**Comment by Marcus98T** [comment]
@ayaka14732 OK, I am aware of this SHS Classic thing, next thing I suppose I might need to produce a list of glyphs that need remapping to different CIDs so it's closer to 源樣明體, but I don't have the time now. Case closed regardless.
