### ISSUE TITLE
「起」字

### ISSUE THREAD

**Issue by kevite** [ButTaiwan/genyo-font#3]
看起來「起」字的「走」部件，空隙可能有點太大。
![screen shot 2017-11-02 at 00 22 18](https://user-images.githubusercontent.com/27000939/32309897-1202ec28-bf65-11e7-81af-8eca654bcdb9.png)

**Comment by ButTaiwan** [comment]
本專案不造新的字符，所有字符都應來自思源宋體本身。
有關字符設計的問題，必須向思源宋體專案反應。
