### ISSUE TITLE
字的高度低於思源宋體

### ISSUE THREAD

**Issue by ayaka14732** [ButTaiwan/genyo-font#30]
以下是思源宋體韓國版與源樣明體的對比，可以看到源樣明體的高度低於思源宋體：

![](https://user-images.githubusercontent.com/68557794/98188557-2e527c80-1f4e-11eb-98ce-c28344676477.gif)

**Comment by ButTaiwan** [comment]
源樣沒有改過高度。這是 render 環境的問題，很有可能在不同軟體上有不同表現。
我只能保證在這個源X系列中全部有相同的高度、行高。

換句話說，如果真公開OTF版本，很有可能OTF版本會跟TTF會有不同的高度。因為這都倚賴軟體端的實作。
