### ISSUE TITLE
設置 OS/2.fsSelection bit 5 跟 head.macStyle bit 0 以正确鏈接字體

### ISSUE THREAD

**Issue by ayaka14732** [ButTaiwan/genyo-font#32]
如果要 Microsoft Office Word 裏面的 **`B`** bold button 按時自動加載 Bold 版，需要設置 [`OS/2.fsSelection`](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fss) bit 5 跟 [`head.macStyle`](https://docs.microsoft.com/en-us/typography/opentype/spec/head#macstyle) bit 0 以正确鏈接字體 (style linking)，否則 Word 会自行偽加粗。（這個是真的醜）

(<https://github.com/ayaka14732/FanWunMing/issues/6#issuecomment-731037802>)

**Comment by ButTaiwan** [comment]
這是故意不連結的。

連結的話，在字型選單就會找不到Bold字重。需要選Regular再加粗才能用。
這也很不直覺。（多數使用者都不知道怎麼在Word找到思源本家的Bold字重…）

既然連結了也只對Regular一個字重支援加粗，其它幾個字重還是沒效。
那不如把所有字重在選單打散，找字型比較簡單。

**Comment by hfhchan** [comment]
+1 @ButTaiwan 
華康出的多字體系列，貌似也是打散不合併

**Comment by NightFurySL2001** [comment]
我觉得链接比较好，毕竟使用 Word 的人更多时间是直接按加粗按钮，不会耗时间在 menu 里面找 Bold 字重/更换字体。如果不链接，伪加粗的情况很容易发生。
https://github.com/adobe-fonts/source-han-sans/issues/101
https://github.com/adobe-fonts/source-han-sans/issues/103
https://github.com/adobe-fonts/source-han-sans/issues/190

**Comment by ButTaiwan** [comment]
各論壇詢問「找不到Bold字重」的問題屢屢有人發問，表示link起來反而會在Word等軟體令使用者困惑。
而且真的想要用Bold時，必須去找Regular再選粗體這種操作行為相當不直覺。

而且就算link起來，這也只適用於Regular。例如還是無法解決Light/Medium的偽加粗問題，在不同字重造成不同行為。
那倒不如讓所有weight都有一樣的使用體驗：一律從字型選擇粗細。

我是做這個選擇。
有人要自己fork別的版本我沒意見，反正開源。

**Comment by hfhchan** [comment]
參考 Hoefler&Co 做法：
https://www.typography.com/faq/106
