### ISSUE TITLE
源樣系列的破折號位置問題

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#33]
在橫排之時，源樣系列中的「⸺」（U+2E3A）的位置偏低（如下圖一）
而在直排之時，源樣系列中的「——」（U+2014 *2）與「――」（U+2015 *2）皆偏右；「⸺」（U+2E3A）的位置則是偏左（如下圖二）

下面兩張圖從左到右、從上到下依序為：「——」（U+2014 *2）、「――」（U+2015 *2）、「⸺」（U+2E3A）

![01](https://user-images.githubusercontent.com/42777336/107742191-8ec13900-6d49-11eb-9a14-a67851b20514.png)

![02](https://user-images.githubusercontent.com/42777336/107742197-9254c000-6d49-11eb-88cf-30dad7819656.png)

**Comment by ButTaiwan** [comment]
三倍長是故意拿掉的，留下垂直高度超高的符號，整個字型的bbox都因此變很高，不知道會有什麼不良影響。

**Comment by ButTaiwan** [comment]
我覺得問題在實際上中文破折號到底是用什麼符號，支援愈多不同的版本只會讓標點符號運用情形更紛歧。
如果慣例是兩個U+2014或U+2015，是否不要再出現其他選擇，能讓文件使用情形更統一一些．

**Comment by chlbc** [comment]
在 W3C 的[《中文排版需求書》](https://www.w3.org/TR/clreq/#categories_and_usage_of_punctuation_marks)的 3.1.1.2 中，有寫說：「推薦使用占兩個漢字寬度的U+2E3A TWO-EM DASH [⸺]，但通常也使用兩個連續的U+2014 EM DASH [—]來實現。」
而 U+2E3A 本身也比較符合破折號本身的「佔兩格的一個符號」的概念，因此還是建議大大把 U+2E3A 作為中文的破折號來處理。

而上面測試直排右偏的環境是：
Microsoft 365 的 Microsoft Word MSO 16.0.13127.21062 64位元版

**Comment by ButTaiwan** [comment]
V2.000 已支援 U+2E3A，直排已經確認置中對齊了。
