### ISSUE TITLE
建議從思源本家加入「⸻」（Three-Em Dash; U+2E3A）符號

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#34]
如題，希望大大可以從思源本家加入「⸻」（Three-Em Dash; U+2E3A）符號，並在橫排、直排時對齊漢字中線

**Comment by ButTaiwan** [comment]
三倍長是故意拿掉的，留下垂直高度超高的符號，整個字型的bbox都因此變很高，不知道會有什麼不良影響。
而且中文標點符號本來就沒有３倍長的定義。
