### ISSUE TITLE
括弧系の全角文字にプロポーショナルと等幅が混在している

### ISSUE THREAD

**Issue by Phroneris** [ButTaiwan/genyo-font#36]
日本語で書いてもよろしいのでしょうか？

---

全角括弧系の文字のうち、`（）` `｛｝` `［］` の3種類が等幅のままになっているようです。
いずれも、カギ括弧 `「」` などと同様のプロポーショナルな幅に統一されている方が嬉しいです（特に丸括弧 `（）`）。

下記のスクリーンショットは、日本の動画編集フリーソフト「AviUtl」で GenYoMin-H を表示したものです。
AviUtlではOTFの高度な機能が全く利用できないので、源ノ明朝 Heavyの骨太な字体をプロポーショナルで使いたい時に、TTFの源様明朝がものすごく役立ちます。
便利なフォントをありがとうございます。

スクリーンショット：
![genYoMin-kakko](https://user-images.githubusercontent.com/9891867/133777415-5db5b18a-38c9-4e48-b642-cca24849983f.png)

スクリーンショットの文字列：
```
字あぁ字（）字あぁ字
字あぁ字［］字あぁ字
字あぁ字｛｝字あぁ字
字あぁ字〈〉字あぁ字
字あぁ字《》字あぁ字
字あぁ字〔〕字あぁ字
字あぁ字「」字あぁ字
字あぁ字『』字あぁ字
字あぁ字【】字あぁ字
字あぁ字‘’字あぁ字
字あぁ字“”字あぁ字
```

詳細な環境情報：
- 源様明朝 v1.501
- AviUtl v1.00
- AviUtl 拡張編集 v0.92
- Windows 7 64-bit

**Comment by ButTaiwan** [comment]
記号をプロポーションにしたのは、まさに映像編集ソフトやプレゼンソフトでの利用を想定していました。

確かに全角丸括弧は忘れていましたね…。
ほかにプロポーションは不便で、全角にしてほしいというリクエストもありましたので、悩むところです。
この点については、ほかにいい解決策があるか考えています。


なお、源様シリーズは書体数もフォント数もかなりありまして、簡単な更新でも大仕事になりがち・・・
最近ほかのプロジェクトを中心にやっていますので、しばらくここの更新はないと思います。（特に年内は…）

ベースラインと文字幅が若干違うものの、当面の間、これらの記号は半角のものでご代用ください。
ちょうど () [] {} ですから…。

**Comment by Phroneris** [comment]
> ほかにプロポーションは不便で、全角にしてほしいというリクエストもありましたので、悩むところです。

ああ、そちらのIssueも拝見しました。
源様明朝に何を求めるかという点で、色々な方面からの意見があり得るのを感じました。
私としては、源様明朝には「統一的にプロポーショナルであること」を期待して使っています。
等幅文字が欲しかったら源ノ明朝を使えば済む話ですし…。いや、行の高さとかの違いもありますが。

とはいえ、フリーのものですので無理の無い範囲で検討していただければ十分です。
これほど巨大な字体群を管理する労力は察するに余りあります。
幸い、AviUtlのテキスト表示では、直後の文字の座標をずらす `<p+X,+Y>` という記法が使えます。
調査してみたところ、フォントサイズの半分（の小数切り捨て）の値でX座標をマイナスにずらしてやると丁度良い表示になるようなので、ユーザー側としてはひとまずはこれで代用できると思います。

スクリーンショット：
<img src="https://user-images.githubusercontent.com/9891867/133895661-20e5855d-5fe2-40e4-9758-663d6d911cc9.png" width="683" height="384">

スクリーンショットの文字列（フォントサイズ34）：
```
字あぁ字（）字あぁ字
字あぁ字<p-17,+0>（）<p-17,+0>字あぁ字
字あぁ字「」字あぁ字
```

ご検討・ご対応を気長にお待ちしております。

**Comment by ButTaiwan** [comment]
V2.000 がリリースされました。
等幅（無印）とプロポーション（P印）の２フォントに分けました。
引き続きよろしくお願いいたします。

**Comment by Phroneris** [comment]
確認できました。

![genYoMin2](https://github.com/user-attachments/assets/bacc80ff-d93a-4b43-af4d-9563b9ed83c4)

```
<s,源様明朝 H>等幅：字あぁ字（）字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字（）字あぁ字
<s,源様明朝 H>等幅：字あぁ字［］字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字［］字あぁ字
<s,源様明朝 H>等幅：字あぁ字｛｝字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字｛｝字あぁ字
<s,源様明朝 H>等幅：字あぁ字〈〉字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字〈〉字あぁ字
<s,源様明朝 H>等幅：字あぁ字《》字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字《》字あぁ字
<s,源様明朝 H>等幅：字あぁ字〔〕字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字〔〕字あぁ字
<s,源様明朝 H>等幅：字あぁ字「」字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字「」字あぁ字
<s,源様明朝 H>等幅：字あぁ字『』字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字『』字あぁ字
<s,源様明朝 H>等幅：字あぁ字【】字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字【】字あぁ字
<s,源様明朝 H>等幅：字あぁ字‘’字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字‘’字あぁ字
<s,源様明朝 H>等幅：字あぁ字“”字あぁ字<p500,-0><s,源様明朝P H>P：字あぁ字“”字あぁ字
```

環境：

- 源様明朝 v2.000
- AviUtl v1.10
- AviUtl 拡張編集 v0.92
- Windows 10 64-bit

どちらもそれぞれ統一できていると思います。
お疲れ様でした！
