### ISSUE TITLE
字形要改變

### ISSUE THREAD

**Issue by Marcus98T** [ButTaiwan/genyo-font#37]
䏕 > 改成思源宋體TW, 不是 JP (源樣黑體已經有TW字形)
諲 > 改成源ノ明朝JP v1.001, 不是 KR/TW
<img width="297" alt="Screenshot 2021-09-29 at 03 13 43" src="https://user-images.githubusercontent.com/10541683/135151090-616ea4ef-74ce-456d-b576-138ee6a5a16a.png">

**Comment by Marcus98T** [comment]
佢 -> TW/HK 字形
哥棗 -> v2 JP 字形
<img width="724" alt="Screenshot 2021-11-15 at 16 52 29" src="https://user-images.githubusercontent.com/10541683/141751263-d17cf422-8e76-45c7-8f12-f16ed8a40941.png">

**Comment by Marcus98T** [comment]
佢駏螶 -> 思源宋體TW字形（黑體也有這樣的問題）
<img width="453" alt="Screenshot 2021-11-21 at 20 23 23" src="https://user-images.githubusercontent.com/10541683/142761610-8ef7c762-cff4-49cc-a1eb-c3595e76128e.png">
<img width="455" alt="Screenshot 2021-11-21 at 20 24 06" src="https://user-images.githubusercontent.com/10541683/142761635-4d3e1c65-8e26-4afa-bddf-3088cc83a7a5.png">

**Comment by ButTaiwan** [comment]
老實說我沒有看過鉛字的巨真的寫成工的。

**Comment by Marcus98T** [comment]
香港鉛字的巨字，上下面的橫真的出頭。來自FB的傳承字形之美。
<img width="948" alt="Screenshot 2021-11-21 at 22 25 04" src="https://user-images.githubusercontent.com/10541683/142765865-dc157167-5b32-4237-b5cb-6d4a934e39db.png">

我看字形巨部還是要多一致。但是姖炬只有台標字形。v2思源宋體TW的「巨」字用CN字形（是bug），所以暫時用KR版。

<img width="1138" alt="Screenshot 2021-11-21 at 22 35 31" src="https://user-images.githubusercontent.com/10541683/142766225-8e25fde7-3ffd-4461-acdd-4a20efbcacb6.png">

P.S. 思源宋體已經在v2了，若有時間我還要backport一些事。

**Comment by Marcus98T** [comment]
壓 -> v2 思源宋體 CN 字形（僅TW版）
<img width="292" alt="Screenshot 2021-11-21 at 22 49 39" src="https://user-images.githubusercontent.com/10541683/142766783-bd2b4f84-a894-4c36-99b7-d7a5064db632.png">

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/142767400-f73b5601-f5fc-409b-a4c2-cf2c78341a4a.png)

**Comment by Marcus98T** [comment]
我看臺灣與香港的鉛字有點不同。還是要（自修）改成JP式字形？

<img width="1440" alt="Screenshot 2021-11-21 at 23 23 12" src="https://user-images.githubusercontent.com/10541683/142768047-21544bb4-626c-4ff6-8df7-91dbf979ace4.png">

紅色 - 缺字（使用楷體）
橙色 - 巨有出頭（JP表外字形）
白色 - 巨沒有出頭（JP字形）
藍色 - CN字形

看還是𠰠缺字（僅TW明體），v2思源宋體HK有𠰠字。

**Comment by Marcus98T** [comment]
「勇」字不一致。要改CN或者TW字形？
<img width="501" alt="Screenshot 2021-11-22 at 00 39 12" src="https://user-images.githubusercontent.com/10541683/142770900-df8ef34b-2344-4e71-a82b-1c315c93dd22.png">

**Comment by ButTaiwan** [comment]
其實還好，部件統一一直都不是主要考量。何者順眼而已。

**Comment by Marcus98T** [comment]
所以意味著臺灣鉛字部件也不統一嗎？我看還是香港鉛字部件有多一點統一。

**Comment by Marcus98T** [comment]
礼 (U+793C) -> U+FA18. 僅TW版，雖然是簡體字但是有舊字形的「礼」字。

<img width="198" alt="Screenshot 2021-11-30 at 16 34 01" src="https://user-images.githubusercontent.com/10541683/144015248-7a9795f3-bb29-4965-a497-42bf3ff953bb.png">

**Comment by Guest-615695028** [comment]
最好的辦法是學習[一點明朝](https://github.com/ichitenfont/I.Ming)。

**Comment by ButTaiwan** [comment]
> 最好的辦法是學習[一點明朝](https://github.com/ichitenfont/I.Ming)。

非本專案目標。

**Comment by Marcus98T** [comment]
大部分的問題都在v2.100已解決。現在可以關閉這個issue。
