### ISSUE TITLE
添加「ヒゲ」

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ButTaiwan/genyo-font#4]
近幾天發現「[源暎こぶり明朝](https://okoneya.jp/font/genei-koburimin.html)」字型給一些字的捺加上了被稱作「ヒゲ」的筆畫（不知道用中文怎麽翻譯），不知源樣明體可否也這樣做？

![如圖](https://i.imgur.com/QTMZVAO.png)

**Comment by ButTaiwan** [comment]
可以，只是要找到思源宋體裡有收ヒゲ的所有glyph。
因為沒有特定的feature可以識別，感覺是個全人工的工作orz...
畢竟源樣收了所有漢字，這會滿花時間的。

**Comment by cathree3** [comment]
可稱爲斧點｡ 斧點不應看作字形差異､ 而是設計風格的捨取､ 我建議思源明體統一設計風格｡https://github.com/adobe-fonts/source-han-serif/issues/36

**Comment by KrasnayaPloshchad** [comment]
我發現「乀」字就有這樣的設計。

**Comment by KrasnayaPloshchad** [comment]
我發現思源宋體的「乀」字就已經有這樣的設計，切換為韓語就能顯現。

**Comment by ButTaiwan** [comment]
Ver 1.300 版已將這些字選擇有ヒゲ的版本。（TW/JP都是）
![image](https://user-images.githubusercontent.com/5418570/45954269-2457b300-c03f-11e8-889d-af3db2860a8b.png)
