### ISSUE TITLE
可以variable-font化

### ISSUE THREAD

**Issue by cang-mang** [ButTaiwan/genyo-font#41]
思源宋體都已經基於可變字體（variable font）技術來做了，并有单独的韩式漢字ttf檔，源樣明體可以考虑基於這個做。

**Comment by ButTaiwan** [comment]
此專案當時使用的工具目前似乎還沒完全支援可變字體，考慮到程式碼移轉成本龐大，主要使用需求也不大，短期內應該是不會有任何製作為可變字型的計畫。

**Comment by chlbc** [comment]
近日 Microsoft 的 Cascadia Code 等寬字型正在製作包含 CJK 字符的版本——Cascadia Next，目前釋出的第一版是採用思源黑體 TW，而製作方也正在徵求意見。其中[有討論指出 TW 版的字形問題](https://github.com/microsoft/cascadia-code/discussions/762#discussioncomment-10481300)，不過製作方似乎只考慮採納有 VF 版的字型。大大或許可以考慮釋出單純源樣黑體的 VF 版，嘗試遞交給製作方試試看？
