### ISSUE TITLE
线装书排版字体求助

### ISSUE THREAD

**Issue by chianjin** [ButTaiwan/genyo-font#42]
我正在尝试使用 LaTeX 作线装书的排版 [https://github.com/chianjin/zhvt-classic](https://github.com/chianjin/zhvt-classic)
目前采用的主字体是 Source Han Serif SemiBold。

![dax](https://user-images.githubusercontent.com/45473376/185149797-03c2dc13-4e5f-4c62-83d1-f8a544634c4a.jpg)

有人推荐源樣明體，效果相当好。也尝试了源流明體，瘦长的字形，效果的确不错，但是字面灰度太大，版面看起来很黑，不是很清爽。希望能在源流明體基础上发布一套宽高比 0.9 的旧字形字体。

另外希望能发布一套在发布一套宽高比 0.5 的字体，以便更好的实现半宽夹注排版。目前尝试的方法是宽度收缩的方法，但由于走之的捺、包心的弯钩等与竖差不多粗细的横向笔画不能同时收缩，看起来很不协调。

![屏幕截图 2022-08-17 210921](https://user-images.githubusercontent.com/45473376/185149922-85b674dd-149f-4895-b90d-e00ce6db52fb.jpg)

希望能够得到帮助

**Comment by ButTaiwan** [comment]
> 希望能发布一套在发布一套宽高比 0.5 的字体
辦不到。

**Comment by chianjin** [comment]
那么，0.9 宽高比的，能办到吗？

**Comment by ButTaiwan** [comment]
跟你自己壓縮是沒有差別的。

**Comment by chianjin** [comment]
好吧
