### ISSUE TITLE
韓文諺文增加請求，以及部分軟體上的粗體使用問題

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#44]
But 大大您好，非常謝謝您製作了源樣系列字型。自從好幾年前這個系列推出後，個人在網頁顯示、簡報、報告，或者是影片字幕之類的場合都有使用這些字型，真的超好用的！
而這次主要是想提出兩個關於源樣系列的相關使用問題與請求，希望大大是否可以考慮看看能否列入源樣系列未來的更新之中。

### 一、希望能夠增加韓文諺文的支援
在將源樣系列字型使用在網頁顯示、或者是使用在某些軟體（像是某些可以設定介面字型的遊戲）時，有時候會遇到一些韓文。如果是在網頁上的韓文的話，多半可以 Fallback 到其他黑體上，因此頂多就是字重比較不合；但在一些軟體或遊戲中可能在玩家 ID 之類的地方會有韓文，這時有時候卻會 Fallback 到一些風格很不搭配的字體，有些甚至會直接豆腐或空白。因此想詢問 But 大大是否可以考慮看看未來加上對韓文諺文的支援呢

### 二、在 PowerPoint 和一些軟體中，使用 Bold 字重的問題
現行源樣系列的 Bold 字重沒有和 Regular 連結，在很多需要單獨選擇 Bold 字重的場合真的滿實用的，但是在一些場合則否。像是在 PowerPoint 中，因為不能像 Word 一樣使用樣式功能來處理粗體，因此目前情況下個人習慣使用佈景主題字型來統一管理：
![image](https://github.com/user-attachments/assets/953b8196-6bdf-4c55-92ce-884f6b290410)
在一般有把 Regular 和 Bold 連結的字型中，要使用 Bold 就可以直接按粗體按鈕，而要更換字型也可以透過修改佈景主題的字型來快速更換，在更換後 Bold 字重的字型也會隨佈景主題字型的更換一起更改。
但是如果是源樣系列的話，我這邊目前的方案是把 Bold 字重設為標題字型，這樣就可以在內文需要用到粗體時，將字型改成標題字型，達到和前述一樣的效果（要更換整篇的字型時可以透過修改佈景主題的字型來快速更換）。
但是如果標題想用 Light 字重的話，就沒辦法這樣直接處理，如果在需要更換字型時就會比較不方便。

此外，在網頁瀏覽或是一些會用到粗體的軟體中，通常沒辦法單獨設定粗體的字型，因此就會發生暴力加粗的情況，會導致比較不那麼美觀和易讀。
因此，想詢問大大是否能夠考慮額外出一個只有 Regular 和 Bold 字重、而且有做 font link 的特殊版本呢？（可能和原版源樣有著不同後綴之類的）這樣不僅能夠使用原版滿足一般的使用情況之外，更可以在這些會需要用到粗體、卻不能單獨指定粗體場合使用

以上，最後再次謝謝 But 大大做出如此好用的系列字型！

**Comment by ButTaiwan** [comment]
> 一、希望能夠增加韓文諺文的支援
很可惜的，因為韓文光是組合後就占用了 11,172 個字符，這還不包括一些 jamo。
本專案為了收錄盡量多的漢字，目前就是透過排除掉韓文來控制檔案大小的。
另一方面移掉韓文的連續碼位空間目前也用來放置台羅、台客語漢字等補字，就算只支援 Unicode 1.0 的 2,350 個韓文音節，也會碰到缺乏連續空間不好管理新增字符的問題.....

> 二、在 PowerPoint 和一些軟體中，使用 Bold 字重的問題
由於 Windows 的限制，一旦定義 font link，就會從字型選單裡消失，故目前評估後傾向拿掉 font link。
要另外出個 font link 版本的粗體技術上好像可行，但....又要因此多 32 個字型檔 (嘆)

**Comment by chlbc** [comment]
> 很可惜的，因為韓文光是組合後就占用了 11,172 個字符，這還不包括一些 jamo。
本專案為了收錄盡量多的漢字，目前就是透過排除掉韓文來控制檔案大小的。
另一方面移掉韓文的連續碼位空間目前也用來放置台羅、台客語漢字等補字，就算只支援 Unicode 1.0 的 2,350 個韓文音節，也會碰到缺乏連續空間不好管理新增字符的問題.....

了解，原本想說現代韓文只有 21 個母音＋19 個子音＋399 個基本組合，沒想到竟然有那麼多個字符，看來這種情況只能回去使用思源本家了

> 由於 Windows 的限制，一旦定義 font link，就會從字型選單裡消失，故目前評估後傾向拿掉 font link。
要另外出個 font link 版本的粗體技術上好像可行，但....又要因此多 32 個字型檔 (嘆)

確實拿掉 font link 還滿好用的，像是有些 Galgame 指定字型時沒有粗體選項，這時候沒有做 font link 的話 Bold 字重就會出現在字型選單內了；而出特殊版本在某種意義上確實感覺有點冗餘，但偏偏需要用到粗體卻不能單獨指定粗體字型情況感覺也沒有想像中的那麼少，如果沒有特殊版本的話就只能選擇讓程式暴力加粗，或者是改用其他字型了（雖然一般使用者好像沒有很在意暴力加粗？望向那個常常被加粗的標楷體）。因此還是會希望大大能考慮多出這個特殊版本

**Comment by KrasnayaPloshchad** [comment]
>了解，原本想說現代韓文只有 21 個母音＋19 個子音＋399 個基本組合，沒想到竟然有那麼多個字符，看來這種情況只能回去使用思源本家了

思源裏面的韓文還有一個獨特的設計，就是每個韓文字形都比漢字窄 7%，為此我還發了個 issue 要求 Adobe 給追加 `wdth` 變量軸。

> 確實拿掉 font link 還滿好用的，像是有些 Galgame 指定字型時沒有粗體選項，這時候沒有做 font link 的話 Bold 字重就會出現在字型選單內了；而出特殊版本在某種意義上確實感覺有點冗餘，但偏偏需要用到粗體卻不能單獨指定粗體字型情況感覺也沒有想像中的那麼少，如果沒有特殊版本的話就只能選擇讓程式暴力加粗，或者是改用其他字型了

我在網路上發現最新版的微軟 Office 已經開始用下拉選單的方式切換粗體（[就像這樣](https://mattesontypographics.com/)），不知拿掉 font link 會不會發生問題？如果會的話，那我建議考慮推出可變字型的版本。

**Comment by ButTaiwan** [comment]
> 如果會的話，那我建議考慮推出可變字型的版本。

目前整個轉檔、調整的工具，並不支援VF。
另外，之前評估了一下，就算把整個流程的工具改版，改用支援VF的版本整個重新改寫（規模龐大），但目前的合併外框與VF原稿，面對的問題完全不同…
舉個最簡單的圓體拔腳為例，現在是從外框繞一圈，去找出疑似腳的外框。但VF版本，口的下面那條橫線根本是另外一條外框，會變成既有演算法會完全沒有辦法識別哪裡是腳。
轉圓角的問題會更大，由多個筆劃構成的部件，現行演算法是針對藍色的部分去算圓角化，但若針對VF外框處理，則紅色部分都會被轉圓角，可預期效果會非常奇怪。
所以本專案可判對應該是很難VF化。

![image](https://github.com/user-attachments/assets/22c452bc-e39d-4723-b5f4-e920f54d648a)

**Comment by ButTaiwan** [comment]
> 了解，原本想說現代韓文只有 21 個母音＋19 個子音＋399 個基本組合，沒想到竟然有那麼多個字符，看來這種情況只能回去使用思源本家了

初聲19 * 中聲21 * 終聲28 = 11172（Unicode所收的所有組合）

Anyway，韓國國內最常用的編碼KS X 1001只有收2350種。V2.100嘗試只收了這2350個字與94個字母，應該可以應付99.99%韓文使用情境。

> 
> > 要另外出個 font link 版本的粗體技術上好像可行，但....又要因此多 32 個字型檔 (嘆)

最後的解決方案，僅ttc版本支援，-B.ttc裡本來包4個字型，改成包8個字型（TW、TC、JP、PJP的B版跟X版），B跟X實質是一樣的字型，只差在X版用於R的粗體link。
安裝R.ttc跟B.ttc後，應該R版就有粗體可用了。

**Comment by chlbc** [comment]
> 我在網路上發現最新版的微軟 Office 已經開始用下拉選單的方式切換粗體（[就像這樣](https://mattesontypographics.com/)），不知拿掉 font link 會不會發生問題？

如果最新版如果加入下拉選單的話，感覺拿掉 font link 還是會不太方便，主要的原因還是在於 PPT 沒有像 Word 一樣有「樣式」功能可以統一控制字型，因此只能使用「佈景主題字型」來達成類似的效果，但偏偏「佈景主題字型」只能設定「標題」和「本文」兩種；此外，一些 PPT 的範本又會在某些地方使用粗體按鍵設的粗體，有的時候只改「佈景主題字型」卻又沒注意到的話，很容易有自動加粗的字體沒改到。
因此，感覺 font link 的版本還是有它的必要性存在。

**Comment by chlbc** [comment]
非常謝謝大大這次的改版！這次改版後確實感覺變得更好用了～

> Anyway，韓國國內最常用的編碼KS X 1001只有收2350種。V2.100嘗試只收了這2350個字與94個字母，應該可以應付99.99%韓文使用情境。

我這邊測試後，確實一般會用到的韓文情境都能使用了！

> 最後的解決方案，僅ttc版本支援，-B.ttc裡本來包4個字型，改成包8個字型（TW、TC、JP、PJP的B版跟X版），B跟X實質是一樣的字型，只差在X版用於R的粗體link。

了解，這個方案真的滿讚的，我這邊使用在那些會加粗的環境也能正常運作了！

不過我這邊偶然發現一個問題，就是不知為啥在 Windows 10 檔案總管的字體圖示預覽好像有點怪怪的，V2.000 和 V2.001 都有這個問題，反而是 V1.501 是正常的。
雖然不影響實際使用，但還是和大大回報下。

| 版本 | 檔案總管截圖 |
| --- | --- |
| V1.501 | ![image](https://github.com/user-attachments/assets/7f4f168f-01a2-4794-8dac-c1f4cc2d9271) |
| V2.000 | ![image](https://github.com/user-attachments/assets/3dc5a151-5af6-4c6d-b5eb-fd4e5c52de8e) |
| V2.100 | ![image](https://github.com/user-attachments/assets/2e4b73e1-ea0a-423f-b497-759ce490460f) |

**Comment by ButTaiwan** [comment]
> 不過我這邊偶然發現一個問題，就是不知為啥在 Windows 10 檔案總管的字體圖示預覽好像有點怪怪的

![image](https://github.com/user-attachments/assets/e102fc9f-2c0f-4543-9855-0d9fc111a36b)
![image](https://github.com/user-attachments/assets/5c261ba6-8406-4f26-9930-e5eaa0a705b9)

我在手邊的 Win 10、Win 11 無法重現一樣的問題，請問重開機後還是一樣的情形嗎？
有時候可能是因為 Windows 的 font cache，在字型改版後，還嘗試去讀原來舊的 gid 造成的。

**Comment by chlbc** [comment]
應該是大大講的那樣沒錯，我這邊重開機後 V2.100 就正常了
![image](https://github.com/user-attachments/assets/dbd3f362-a1e3-4ad7-af45-149efe024718)

但反而是 V2.000 開始發病了www
或許是字型名稱一樣的關係？
![image](https://github.com/user-attachments/assets/b51f017b-a204-40af-ae27-d0494622aac8)

**Comment by ButTaiwan** [comment]
有可能，當安裝字型以後，Windows 縮圖有可能會用 font cache 的 gid 等資訊去嘗試讀取識別名稱相同的字型檔。
V2.100為了塞韓文與新增的100個漢字，對文字順序有比較大幅度的調整，gid應該是全變了。

**Comment by chlbc** [comment]
瞭解了。不過在實際使用上好像也沒有太大的影響就是。

另外剛才把介面字型設為源始黑體並試用了幾個小時之後，
除了韓文和粗體支援之外，也確實感覺字形不一致的情況少了很多。
再次謝謝大大這次的改版！
我這邊先關 Issue 了。
