### ISSUE TITLE
破折號（U+2014）在 V2.000 的 TW/TC 版本中無法正常連接

### ISSUE THREAD

**Issue by chlbc** [ButTaiwan/genyo-font#46]
如圖所示，測試環境是 Word 2021（另外思源本家 JP 的結果和源起 PJP 是一樣的）：
![image](https://github.com/user-attachments/assets/727f78bd-35d7-4cc8-a2a7-d9569422c0a7)

另外也想詢問大大，在有三個以上破折號的情況下，是像源起 JP 版一樣兩個兩個連起來比較好呢？還是游黑體那樣全部連起來比較好呢？

以前在使用 V1.501 時曾經在日中翻譯時遇過一種情況：
> 日文：「あ——————」
中文：「啊——————」

這種情況下，日文因為採用游黑體的緣故，能夠直接將所有破折號連成一直線；但源樣 V1.501 卻是兩個兩個連接，感覺全部連成一直線比較美觀一點，但不太確定標準是怎麼規定的。

**Comment by ButTaiwan** [comment]
我測試是正常的，不知道你的測試環境是？
![image](https://github.com/user-attachments/assets/2e563e92-6d82-4c55-a5ee-0398698416b3)

> 另外也想詢問大大，在有三個以上破折號的情況下，是像源起 JP 版一樣兩個兩個連起來比較好呢？
思源就是因為有橫排、直排的3倍破折號，造成FontBBox的垂直高度太大，因此一直有在Illustrator之類的軟體文字框過大、很難選到正確行的問題。所以刻意拿掉3倍破折號。

> 這種情況下，日文因為採用游黑體的緣故，能夠直接將所有破折號連成一直線
這沒有標準答案，游黑體大概是單純提供一個左右都碰到字符邊框的橫線（字符寬1000，橫線也寬1000），這樣好處是無論幾個都能接起來，壞處是跟前後漢字顯得太緊，而且散排（字間大於0時）時就會斷開；思源的做法是將兩個U+2014、U+2015取代成一個兩倍寬的字符，橫線左右稍微留縫（例如字符寬2000，橫線寬1900置中），這樣的好處是跟漢字之間的距離較自然，即使散排也能連在一起（不過會造成不同行無法對齊），缺點就是要多長的破折號就要做幾個不同版本，不然就會幾個幾個一組斷開，但3倍破折號的直排就造成FontBBox的問題，所以我才會拿掉。
我覺得思源的形式距離感比較舒服，所以保留思源原來的做法，只是拿掉3倍版本。如果真的需要很長的線，可以考慮使用表格線──────。

**Comment by chlbc** [comment]
了解，謝謝大大的解說！確實思源這樣的距離感也還滿不錯的

> 我測試是正常的，不知道你的Word會不會字型跑掉了，套用到英文字型之類的？

好像沒有跑掉，我用`破折號——測試`這串文字來測試，文字打完後才套用字型：
![image](https://github.com/user-attachments/assets/8daf576e-f977-47d5-ae52-4bb4e7bb4b77)

但我這邊是連思源黑體、宋體 V2 TW 的 U+2014 都會斷開，只有用思源 JP 版、源樣 V1 TW，還有源樣 V2 JP 版才能連接。
還是是 Word 版本的問題？
![image](https://github.com/user-attachments/assets/78f8bb86-8978-4731-8616-23da6657f758)

**Comment by chlbc** [comment]
發現問題在哪裡了。不知為啥這個版本的連字沒有預設開啟，開啟連字後就能正常連接了
![image](https://github.com/user-attachments/assets/2f74a084-8b50-4500-b7b6-3e01437c8678)
