### ISSUE TITLE
關於“忘”字等字形的疑問

### ISSUE THREAD

**Issue by gannaiju** [ButTaiwan/genyo-font#50]
作者大佬你好。
注意到某些字/部件，相比思源韓版，具有了手寫風格（“亡”字下部的豎折，見下圖：
![Picsew_20241007174227](https://github.com/user-attachments/assets/7fb9d57f-6027-4ca3-bb37-4d6d77526b80)
請問這是傳統字體的風格嗎？謝謝。

**Comment by ButTaiwan** [comment]
在康熙字典，亡字豎折造形呈彎筆，直角彎才是新字形。
![image](https://github.com/user-attachments/assets/a320782d-715a-4b20-9f75-7e4b2fbc91f7)

不過我其實不是很在意這兩種彎筆的區別，但上面的點跟豎點差異過為明顯，所以還是選擇上方寫法。

**Comment by gannaiju** [comment]
受教了，謝謝。
