### ISSUE TITLE
What is difference between GenKiMin2 and GenYoMin2 please ?

### ISSUE THREAD

**Issue by zarniwhoop73** [ButTaiwan/genyo-font#52]
I cannot read Chinese except using Google or Bing translations. I am trying to document available libre fonts, I understand the difference between the TC and TW versions, and can see differences between TC and TW. But the GenKiMin2 and GenYoMin2 TC fonts look identical ?

Is there a general stylistic difference, or some example unicode ideograms which look different ?

**Comment by ButTaiwan** [comment]
GenKi tries to modify some Kai style turns to traditional Mingti / Gothic style, and GenYo keeps original glyphs from Source Han Sans/Serif.

![FB_IMG_1731082475711](https://github.com/user-attachments/assets/8dd75395-387d-4c71-81d1-49d4f183a255)

**Comment by zarniwhoop73** [comment]
Thank you very much.
