### ISSUE TITLE
支援蘇州碼子幻方

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ButTaiwan/genyo-font#6]
我發現有人在維基共享發佈了圖片，裏面是蘇州碼子寫的兩個幻方。
https://commons.wikimedia.org/wiki/File:%E8%98%87%E5%B7%9E%E7%A2%BC%E5%AD%90%E5%AF%AB%E7%9A%84%E5%85%A9%E5%80%8B%E5%B9%BB%E6%96%B9.png
個人建議先利用現有蘇州碼子字元創作新字形，然後利用 `ccmp` 特性實作，但是兩個字元之間必須插入 [ZWJ](https://en.wikipedia.org/wiki/Zero-width_joiner) 才能生效。

**Comment by ButTaiwan** [comment]
本專案不造新的字符，所有字符都應來自思源宋體本身。
