### ISSUE TITLE
一些TW字形可能需要改變 (比如: 最, 即, 明, 朝, 的, etc.)

### ISSUE THREAD

**Issue by Marcus98T** [ButTaiwan/genyo-font#9]
我還以為有些字形還沒有改變，所以提出來。右邊的隱藏字形都在思源黑體/明體字體裡面。

![glyph change](https://user-images.githubusercontent.com/10541683/46363608-1391e780-c6a6-11e8-8c27-fdf379b97706.png)
![default](https://user-images.githubusercontent.com/10541683/46365883-48a13880-c6ac-11e8-9238-14fd60e5b4c1.png)

請參考此鏈接: [https://github.com/MoneMizuno/Genne-Gothic](https://github.com/MoneMizuno/Genne-Gothic)和[這個文件](https://github.com/MoneMizuno/Genne-Gothic/blob/master/Other/Other/CMap%E6%9B%BF%E6%8F%9B%E8%A1%A8_Genne%20Gothic_1.004.ods)。

這些建議包括你所有的字形。原諒我重複issues。多謝。

**Comment by ButTaiwan** [comment]
1. 此次部首統一作業僅限於Big5範圍內（即用一般用注音輸入法容易輸入的字部件不統一者。）故戸、経之類都不在處理範圍。（這次調整字形，是為了解決一般繁體中文文件常用字如青、請部件不統一的問題。而這些非Big5文字，可解讀為使用者故意輸入的，沒必要統一部件。）

2. 部分部件（如月），雖然部份文字確實右側不接觸版本可選。但更多文字沒得選，選了反而造成不統一，多數選擇不改。

3. 橫點，原則上除了少部分文字外都不選。如上所說，只有部份文字能選，選了反而造成部件不統一。

4. 最、冒…類，猶豫到後來的結果是選曰。傳統鉛字（一般印刷品）最常見的寫法是曰。

5. 部份文字是實用性考量（如再、冉兩字不出頭。勺、的、約、釣四字從點。）

**Comment by KrasnayaPloshchad** [comment]
思源黑體/明體字體的K版（不是KR）裡面或許還有隱藏字形亟待發掘。

**Comment by Marcus98T** [comment]
在 Adobe Illustrator CS6 的 Glyphs 中 CAP 到思源黑體/明體日本版的隱藏異體字形。
![source han sans hidden glyphs](https://user-images.githubusercontent.com/10541683/47585115-f394d180-d98e-11e8-8e7b-ce870da3ccab.png)
![source han serif hidden glyphs](https://user-images.githubusercontent.com/10541683/47585792-ed075980-d990-11e8-844c-66a1cafe6963.png)
我相信這些是所有的隱藏字形。

**Comment by Marcus98T** [comment]
P.S. "与写欤, 条, 炭" 字在 TW font 還顯示日本字形，但是它們有隱藏舊字形，需要改變。像"牙"一樣，"鄰圍驎蕣舛"字恢復用日本字形。"韓違燐麟鱗桝" 字有隱藏舊字形。

**Comment by ButTaiwan** [comment]
与写欤 之類，顯然是我個人傾向使用JP字形 :)
是說我覺得會用 ssXX 的人就用本家思源就好XDD

**Comment by Marcus98T** [comment]
”最、冒“選曰以外，這個安排OK？
![screen shot 2018-11-08 at 18 58 03](https://user-images.githubusercontent.com/10541683/48194652-8f0f4480-e388-11e8-8cbc-c6e5044827c8.png)
”空“ 字使用 “儿” 還是 “八” 由你決定。

**Comment by KrasnayaPloshchad** [comment]
> 是說我覺得會用 ssXX 的人就用本家思源就好XDD

微軟 Word 裏面的「字型」設定就有這個。

**Comment by Marcus98T** [comment]
思源黑體v2.000已經發布。但遺憾的是，一些日本字形被刪除了。

https://privatebin.net/?03143d1abad44266#lLTprb0iZ0kArGytyWgjt1DPeaIlVSuTQiJTFV4H+gI=
[Source Han Sans Difference JP.txt](https://github.com/ButTaiwan/genyo-font/files/2599488/Source.Han.Sans.Difference.JP.txt)

此列表描述思源黑體v2.000日本字形的刪除，所以被影響的常用漢字現在使用新字形方式。你應該看的是"Ideographs"。 從這些行中，它們應該包含URO，CI或ExtA（或B，C等）前綴。

暫時沒有圖片。

如果要更新的話，此列表將有所幫助。

**Comment by ButTaiwan** [comment]
> ”最、冒“選曰以外，這個安排OK？
> ”空“ 字使用 “儿” 還是 “八” 由你決定。

我個人還是傾向除了 欤 以外都不改。
例如炭選了等同灰的寫法，結果與碳字又不統一了。

如同 ”最、冒“ 的理由，本計畫的目標一直是「傳統印刷體」。
這不是基於字理或訓詁上的。
而是依（個人印象中）台灣從鉛字時期起在一般報刊印刷物上最常出現的字形為依歸。

p.s. 由於台灣的宋體鉛字實際上多進口自日本，所以可推測應該最接近日本當用漢字表裡定義的舊字體。

**Comment by Marcus98T** [comment]
> 例如炭選了等同灰的寫法，結果與碳字又不統一了。
相反，"碳"有⿸𠂇火，炭有⿸厂火，所以要改成⿸𠂇火就會統一了。
![screen shot 2018-11-23 at 15 57 43](https://user-images.githubusercontent.com/10541683/48932841-d543d680-ef38-11e8-9a07-e6891ae87df1.png)

**Comment by ButTaiwan** [comment]
我要先來去找找台灣傳統鉛字常不常見這個版本的炭，沒有印象有看過。

**Comment by KrasnayaPloshchad** [comment]
我發現這裏有一些字型資源，不知可否拿來參考。
https://code.google.com/p/kingfont

**Comment by ButTaiwan** [comment]
> 我發現這裏有一些字型資源，不知可否拿來參考。
> https://code.google.com/archive/p/kingfont/downloads

那裡都是商業字型，這是盜版行為。

**Comment by Marcus98T** [comment]
> 關於「壓」字建議選「厂」的左邊那撇撇到最下面的版本，比較符合康熙字典的舊字形

思源黑體2.000的簡體版已經有，但是明體還沒有。https://github.com/adobe-fonts/source-han-serif/issues/40#issuecomment-450832401

![screen shot 2019-01-02 at 18 44 01-1](https://user-images.githubusercontent.com/10541683/50588899-2becea80-0ebf-11e9-9206-5e8ee66f07e2.png)

**Comment by KrasnayaPloshchad** [comment]
Unicode 有針對中日韓文字的變體字元技術資料，可以考慮通過運用這種技術讓一些字元切換到隱藏字形。
https://www.unicode.org/reports/tr37/
https://www.unicode.org/ivd/

**Comment by ButTaiwan** [comment]
> Unicode 有針對中日韓文字的變體字元技術資料，可以考慮通過運用這種技術讓一些字元切換到隱藏字形。
> https://www.unicode.org/reports/tr37/
> https://www.unicode.org/ivd/

使用IVS切換異體字的話，最好就要遵造IVD所登錄的異體表去切，才能維持大家看到一樣的異體，這才是IVD/IVS當初創造的本意。
不過實務上只有日本在登錄IVD的異體列表，中文圈對這個機制目前沒什麼興趣。
所以中文字型去支援IVD/IVS實務上沒意義。

**Comment by Marcus98T** [comment]
One more thing.

"呈" 需要用TW字形
"龜" 需要用JP字形
"篠" 需要用JP字形
"肏" 需要用TW字形

順便說說，台北黑體Beta已經發佈 (https://sites.google.com/view/jtfoundry/zh-tw)。雖然字形是新舊混合，作者會親自改字，比如"搧"字。也許，在未來可能使用一些台北黑體的字形。但是，這是一個慢慢的過程，還有，有些他修改的字絕不可能使用傳統字形（比如"送"字）。

**Comment by ButTaiwan** [comment]
> "龜" 需要用JP字形，因為JP字形跟康熙字典體是最像的：

本 project 參考對象是「台灣鉛字印刷時代一般使用的鉛字粒印刷體」為準。
並不是完全以康熙字典為準。

**Comment by ButTaiwan** [comment]
Ver 1.500
![image](https://user-images.githubusercontent.com/5418570/79039312-f763f480-7c12-11ea-9b9c-6f766cb6f685.png)
